on:
  push:
    branches:    
      - 'master'

name: 'Package: Debian GNU + Linux (x86_64)'

jobs:
  deb_x86-64:
    name: Debian GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libgtk-4-1 libgtk-4-common libgtk-4-dev build-essential > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Install 'cargo-deb'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Build & package keywi
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --separate-debug-symbols -- --target x86_64-unknown-linux-gnu
      - name: Upload keywi build artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-keywi.deb.gnu+linux
          path: ./target/debian/keywi_*_amd64.deb
          if-no-files-found: error