# on:
#   push:
#     branches:    
#       - 'master'

# name: 'Build: macOS (ARM64)'

# jobs:
#   mac_aarch64:
#     name: macOS (ARM64)
#     runs-on: macos-latest
#     steps:
#       - name: Checkout codebase
#         uses: actions/checkout@v3
#       - name: Install development dependencies
#         run: |
#           brew update > /dev/null
#           brew install openssl openssl@1.1 > /dev/null
#       - name: Setup Rust toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: nightly
#           target: aarch64-apple-darwin
#           default: true
#           profile: minimal
#       - name: Build Vaultist
#         uses: actions-rs/cargo@v1
#         with:
#           use-cross: true
#           command: build
#           args: --release --target aarch64-apple-darwin
#       - name: Prepare Vaultist for upload
#         run: |
#           cd ./target/aarch64-apple-darwin/release/
#           strip ./vaultist
#           chmod +x ./vaultist
#           tar -cvf aarch64-vaultist.osx.tar \
#           vaultist \
#           libvaultist.dylib \
#           libvaultist.a
#       - name: Upload Vaultist build artifacts to GitHub
#         uses: actions/upload-artifact@v3
#         with:
#           name: aarch64-vaultist.osx
#           path: ./target/aarch64-apple-darwin/release/aarch64-vaultist.osx.tar
#           if-no-files-found: error
