on:
  push:
    branches:    
      - 'master'

name: 'Build: macOS (x86_64)'

jobs:
  mac_x86-64:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          profile: minimal
      - name: Build Keywi
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-apple-darwin
      - name: Prepare Keywi for upload
        run: |
          cd ./target/x86_64-apple-darwin/release/
          strip ./keywi
          chmod +x ./keywi
          tar -cvf x86_64-keywi.osx.tar \
          keywi \
          libkeywi.dylib \
          libkeywi.a
      - name: Upload Keywi build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-keywi.osx
          path: ./target/x86_64-apple-darwin/release/x86_64-keywi.osx.tar
          if-no-files-found: error